name: Nightly

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  windowsBuild:
    name: Windows build
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: build
      run: Scripts/PublishAll.cmd /ni

    - name: Upload to FTP
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTPADDRESS }}
        user: ${{ secrets.FTPUSER }}
        password: ${{ secrets.FTPPASSWORD }}
        localDir: Dist/Packages/
        remoteDir: Nightlies/
